# docker-compose.yml

version: '2'

services:

  mysql:
    image: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: ficha_e
      
    volumes:
      - $PWD/BD:/var/lib/mysql
      - $PWD/scripts/:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - mysql:db
     
  tomcat:
     image: tomcat
     ports:
       - 8888:8080
       - 9000:8000
     links:
      - mysql:db
     environment:
       - JPDA_ADDRESS=8000
       - JPDA_TRANSPORT=dt_socket
        # observe que a aplicacao devera ser montada a partir da pasta onde se localiza o war - note tambem que a url ficara com o nome do arquivo
     volumes:
       - $PWD:/usr/local/tomcat/webapps/
  selenium_hub:
     image: selenium/hub:3.0.1-aluminum
     container_name: selenium_hub
     privileged: true
     ports:
       - 4444:4444
     environment:
       - GRID_TIMEOUT=120000
       - GRID_BROWSER_TIMEOUT=120000
     networks:
       - selenium_grid_internal

  nodechrome:
     image: selenium/node-chrome-debug:3.0.1-aluminum
     privileged: true
     depends_on:
       - selenium_hub
     ports:
       - 5900
     environment:
       - no_proxy=localhost
       - HUB_PORT_4444_TCP_ADDR=selenium_hub
       - HUB_PORT_4444_TCP_PORT=4444
     networks:
       - selenium_grid_internal

  nodefirefox:
     image: selenium/node-firefox-debug:3.0.1-aluminum
     privileged: true
     depends_on:
       - selenium_hub
     ports:
       - 5900
     environment:
       - no_proxy=localhost
       - HUB_PORT_4444_TCP_ADDR=selenium_hub
       - HUB_PORT_4444_TCP_PORT=4444
     networks:
       - selenium_grid_internal

networks:
    selenium_grid_internal:
